### ISSUE TITLE
AsyncSnapshot

### ISSUE THREAD

**Issue by lukepighetti** [s0nerik/context_plus#8]
I totally get the reasoning behind changing the API to use AsyncSnapshot but part of the beauty of context_watch was the simplicity of the API, would have loved to see `.watch` stay as it was, and then add a `.watchSnapshot` with the AsyncSnapshot return type

**Comment by lukepighetti** [comment]
still think the migration bloats the simplicity of the API and would have preferred to see this as `.watchSnapshot` leaving `.watch` as is. 

ended up with this extension which I now have to cart around to all my projects

```dart
extension ValueStreamX<T> on ValueStream<T> {
  T watchValue(BuildContext context) => watch(context).data ?? value;
}
```

**Comment by s0nerik** [comment]
@lukepighetti, looks like the `watchValue` extension you use can be simplified to the `watch(context).data!` or `watch(context).requireData` since context_watch handles a special case of `ValueStream`'s initial value being already present under the hood and returns the data in that case in the same frame.

Regarding the package API design decision, I don't want to get rid of the `AsyncSnapshot` as it allows for keeping the API surface really tiny and easy to remember and use. I love the fact that there's only two additional methods on everything observable: `.watch()` (for observing the whole thing) and `.watchOnly()` (for observing a part of the thing) and don't plan on adding any new methods to the base packages.

However, I think it would be very fairly easy to introduce another "integration" package for rxdart specifically, with the `.watchValue()` and `.watchValueOrNull()` extensions, which would just always return the respective property values of the `ValueStream`. Please let me know if that could be of any value to you.
